AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "sample for aws --version"
Resources:
  lambdalayerawscli:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:903779448426:applications/lambda-layer-awscli
        SemanticVersion: 1.16.213
  SampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      CodeUri: ./func.d
      Runtime: provided
      Environment:
        Variables:
          AWS_ACCOUNT_ID: !Sub "${AWS::AccountId}"
      Layers:
        - !GetAtt lambdalayerawscli.Outputs.LayerVersionArn
      MemorySize: 512
      Timeout: 10


Outputs:
  LayerArn:
    Value: !GetAtt lambdalayerawscli.Outputs.LayerVersionArn
  FuncArn:
    Value: !Ref SampleFunction