AWSTemplateFormatVersion: '2010-09-09'

Metadata:
  AWS::ServerlessRepo::Application:
    Name: amazon-connect-outbound-prompt-call
    Description: "Amazon Connect sample application to place outbound prompt calls"
    Author: Pahud Hsieh
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels: ['connect','cloudwatch','call','pageduty','alarm']
    HomePageUrl: https://github.com/aws-samples/aws-lambda-layer-awscli/tree/master/samples/amazon-connect
    SemanticVersion: 1.0.0
    SourceCodeUrl: https://github.com/aws-samples/aws-lambda-layer-awscli/tree/master/samples/amazon-connect

Transform: AWS::Serverless-2016-10-31
Description: "Amazon Connect outbound prompt call sample"
Parameters:
  LambdaRoleArn:
    Type: String
    Description: OPTIONAL - provide your own Lambda role ARN otherwise I will generate a role for you
    Default: default
  CallCenterRegion:
    Type: String
    Description: AWS Region of your Amazon Connect
    Default: us-east-1
  DestPhoneNumber:
    Type: String
    Description: Destination outbound call number
  ContactFlowId:
    Type: String
    Description: Amazon Connect contact flow ID 
  InstanceId:
    Type: String
    Description: Amazon Connect instance ID
  SrcPhoneNumber:
    Type: String
    Description: Amazon Connect source phone number 

    
Conditions:
  UseDefaultLambdaRoleArn: !Equals [ !Ref LambdaRoleArn, default ]

Resources:
  lambdalayerawscli:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:903779448426:applications/lambda-layer-awscli
        # You should get the latest SemanticVersion with the following aws-cli:
        # aws serverlessrepo get-application --application-id arn:aws:serverlessrepo:us-east-1:903779448426:applications/lambda-layer-awscli --query 'Version.SemanticVersion' --output text
        SemanticVersion: 1.16.216
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      CodeUri: ./func.d
      Runtime: provided
      Role: 
        !If
          - UseDefaultLambdaRoleArn
          - !GetAtt MyLambdaRole.Arn
          - !Ref LambdaRoleArn
      Environment:
        Variables:
          DEST_PHONE_NUMBER: !Ref DestPhoneNumber
          CONTACT_FLOW_ID: !Ref ContactFlowId
          INSTANCE_ID: !Ref InstanceId
          SRC_PHONE_NUMBER: !Ref SrcPhoneNumber
          AWS_ACCOUNT_ID: !Sub "${AWS::AccountId}"
          CALL_CENTER_REGION: !Ref CallCenterRegion
      Layers:
        - !GetAtt lambdalayerawscli.Outputs.LayerVersionArn
      MemorySize: 512
      Timeout: 10

  MyLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Path: /
      Policies:
      - PolicyName: Root
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - connect:StartOutboundVoiceContact
            Resource: '*'
      RoleName:
        Fn::Sub: ${AWS::StackName}-Role

Outputs:
  LayerArn:
    Value: !GetAtt lambdalayerawscli.Outputs.LayerVersionArn
  FuncArn:
    Value: !Ref Function
